// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Job struct {
	ID                 int64          `json:"id"`
	Prefix28           []byte         `json:"prefix_28"`
	NonceStart         int64          `json:"nonce_start"`
	NonceEnd           int64          `json:"nonce_end"`
	CurrentNonce       sql.NullInt64  `json:"current_nonce"`
	Status             string         `json:"status"`
	WorkerID           sql.NullString `json:"worker_id"`
	WorkerType         sql.NullString `json:"worker_type"`
	ExpiresAt          sql.NullTime   `json:"expires_at"`
	CreatedAt          time.Time      `json:"created_at"`
	CompletedAt        sql.NullTime   `json:"completed_at"`
	KeysScanned        sql.NullInt64  `json:"keys_scanned"`
	RequestedBatchSize sql.NullInt64  `json:"requested_batch_size"`
	LastCheckpointAt   sql.NullTime   `json:"last_checkpoint_at"`
}

type Result struct {
	ID         int64     `json:"id"`
	PrivateKey string    `json:"private_key"`
	Address    string    `json:"address"`
	WorkerID   string    `json:"worker_id"`
	JobID      int64     `json:"job_id"`
	NonceFound int64     `json:"nonce_found"`
	FoundAt    time.Time `json:"found_at"`
}

type StatsSummary struct {
	PendingBatches    int64           `json:"pending_batches"`
	ProcessingBatches int64           `json:"processing_batches"`
	CompletedBatches  int64           `json:"completed_batches"`
	TotalBatches      int64           `json:"total_batches"`
	TotalKeysScanned  interface{}     `json:"total_keys_scanned"`
	AvgPcBatchSize    sql.NullFloat64 `json:"avg_pc_batch_size"`
	AvgEsp32BatchSize sql.NullFloat64 `json:"avg_esp32_batch_size"`
	ResultsFound      int64           `json:"results_found"`
	TotalWorkers      int64           `json:"total_workers"`
	ActiveWorkers     int64           `json:"active_workers"`
	PcWorkers         int64           `json:"pc_workers"`
	Esp32Workers      int64           `json:"esp32_workers"`
	ActivePrefixes    int64           `json:"active_prefixes"`
}

type Worker struct {
	ID               string         `json:"id"`
	WorkerType       string         `json:"worker_type"`
	LastSeen         time.Time      `json:"last_seen"`
	TotalKeysScanned sql.NullInt64  `json:"total_keys_scanned"`
	Metadata         sql.NullString `json:"metadata"`
	CreatedAt        time.Time      `json:"created_at"`
}

type WorkerHistory struct {
	ID            int64           `json:"id"`
	WorkerID      string          `json:"worker_id"`
	WorkerType    sql.NullString  `json:"worker_type"`
	JobID         sql.NullInt64   `json:"job_id"`
	BatchSize     sql.NullInt64   `json:"batch_size"`
	KeysScanned   sql.NullInt64   `json:"keys_scanned"`
	DurationMs    sql.NullInt64   `json:"duration_ms"`
	KeysPerSecond sql.NullFloat64 `json:"keys_per_second"`
	Prefix28      []byte          `json:"prefix_28"`
	NonceStart    sql.NullInt64   `json:"nonce_start"`
	NonceEnd      sql.NullInt64   `json:"nonce_end"`
	FinishedAt    time.Time       `json:"finished_at"`
	ErrorMessage  sql.NullString  `json:"error_message"`
}

type WorkerStatsDaily struct {
	ID               int64           `json:"id"`
	WorkerID         string          `json:"worker_id"`
	StatsDate        time.Time       `json:"stats_date"`
	TotalBatches     sql.NullInt64   `json:"total_batches"`
	TotalKeysScanned sql.NullInt64   `json:"total_keys_scanned"`
	TotalDurationMs  sql.NullInt64   `json:"total_duration_ms"`
	KeysPerSecondAvg sql.NullFloat64 `json:"keys_per_second_avg"`
	KeysPerSecondMin sql.NullFloat64 `json:"keys_per_second_min"`
	KeysPerSecondMax sql.NullFloat64 `json:"keys_per_second_max"`
	ErrorCount       sql.NullInt64   `json:"error_count"`
}

type WorkerStatsLifetime struct {
	WorkerID           string          `json:"worker_id"`
	WorkerType         sql.NullString  `json:"worker_type"`
	TotalBatches       sql.NullInt64   `json:"total_batches"`
	TotalKeysScanned   sql.NullInt64   `json:"total_keys_scanned"`
	TotalDurationMs    sql.NullInt64   `json:"total_duration_ms"`
	KeysPerSecondAvg   sql.NullFloat64 `json:"keys_per_second_avg"`
	KeysPerSecondBest  sql.NullFloat64 `json:"keys_per_second_best"`
	KeysPerSecondWorst sql.NullFloat64 `json:"keys_per_second_worst"`
	FirstSeenAt        time.Time       `json:"first_seen_at"`
	LastSeenAt         time.Time       `json:"last_seen_at"`
}

type WorkerStatsMonthly struct {
	ID               int64           `json:"id"`
	WorkerID         string          `json:"worker_id"`
	StatsMonth       string          `json:"stats_month"`
	TotalBatches     sql.NullInt64   `json:"total_batches"`
	TotalKeysScanned sql.NullInt64   `json:"total_keys_scanned"`
	TotalDurationMs  sql.NullInt64   `json:"total_duration_ms"`
	KeysPerSecondAvg sql.NullFloat64 `json:"keys_per_second_avg"`
	KeysPerSecondMin sql.NullFloat64 `json:"keys_per_second_min"`
	KeysPerSecondMax sql.NullFloat64 `json:"keys_per_second_max"`
	ErrorCount       sql.NullInt64   `json:"error_count"`
}
