// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
	"database/sql"
)

type Querier interface {
	// Clear worker assignment for long-stale processing jobs so they can be re-leased
	CleanupStaleJobs(ctx context.Context, thresholdSeconds sql.NullString) error
	// Mark a batch as completed
	CompleteBatch(ctx context.Context, arg CompleteBatchParams) error
	// Create a new batch (job) for a worker
	CreateBatch(ctx context.Context, arg CreateBatchParams) (Job, error)
	// Find an available batch (pending or expired lease)
	FindAvailableBatch(ctx context.Context) (Job, error)
	// Get workers active in the last N minutes
	GetActiveWorkers(ctx context.Context, dollar_1 sql.NullString) ([]Worker, error)
	// Get all results (limited)
	GetAllResults(ctx context.Context, limit int64) ([]Result, error)
	// Get a specific job by ID
	GetJobByID(ctx context.Context, id int64) (Job, error)
	// Get jobs by status
	GetJobsByStatus(ctx context.Context, arg GetJobsByStatusParams) ([]Job, error)
	// Get all jobs assigned to a specific worker
	GetJobsByWorker(ctx context.Context, workerID sql.NullString) ([]Job, error)
	// Get the next available nonce range for a specific prefix
	GetNextNonceRange(ctx context.Context, prefix28 []byte) (interface{}, error)
	// Get usage statistics per prefix
	GetPrefixUsage(ctx context.Context, limit int64) ([]GetPrefixUsageRow, error)
	// Find a result by private key
	GetResultByPrivateKey(ctx context.Context, privateKey string) (Result, error)
	// Find results by Ethereum address
	GetResultsByAddress(ctx context.Context, address string) ([]Result, error)
	// Get aggregated statistics
	GetStats(ctx context.Context) (StatsSummary, error)
	// Get worker information by ID
	GetWorkerByID(ctx context.Context, id string) (Worker, error)
	// Tracks the last prefix assigned to a worker to enable vertical exhaustion
	GetWorkerLastPrefix(ctx context.Context, workerID sql.NullString) (GetWorkerLastPrefixRow, error)
	// Get statistics per worker
	GetWorkerStats(ctx context.Context, limit int64) ([]GetWorkerStatsRow, error)
	// Get all workers of a specific type
	GetWorkersByType(ctx context.Context, workerType string) ([]Worker, error)
	// Insert a new result (found key)
	InsertResult(ctx context.Context, arg InsertResultParams) (Result, error)
	// Lease an existing batch to a worker
	LeaseBatch(ctx context.Context, arg LeaseBatchParams) (int64, error)
	// Update job progress checkpoint
	UpdateCheckpoint(ctx context.Context, arg UpdateCheckpointParams) error
	// Update worker's total key count
	UpdateWorkerKeyCount(ctx context.Context, arg UpdateWorkerKeyCountParams) error
	// Insert or update worker heartbeat
	UpsertWorker(ctx context.Context, arg UpsertWorkerParams) error
}

var _ Querier = (*Queries)(nil)
