// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
	"database/sql"
)

type Querier interface {
	// Clear worker assignment for long-stale processing jobs so they can be re-leased.
	CleanupStaleJobs(ctx context.Context, thresholdSeconds sql.NullString) error
	// Mark a batch as completed
	CompleteBatch(ctx context.Context, arg CompleteBatchParams) error
	// Create a new batch (job) for a worker
	CreateBatch(ctx context.Context, arg CreateBatchParams) (Job, error)
	// Create a long-lived macro job covering the full nonce space for a prefix
	CreateMacroJob(ctx context.Context, arg CreateMacroJobParams) (Job, error)
	// Find an available batch (pending or expired lease, or already assigned to same worker)
	FindAvailableBatch(ctx context.Context, workerID sql.NullString) (Job, error)
	// Find an existing non-completed (macro) job for a given prefix
	FindIncompleteMacroJob(ctx context.Context, prefix28 []byte) (Job, error)
	// Get detailed info about currently active workers for dashboard
	GetActiveWorkerDetails(ctx context.Context) ([]GetActiveWorkerDetailsRow, error)
	// Get workers active in the last N minutes
	GetActiveWorkers(ctx context.Context, dollar_1 sql.NullString) ([]Worker, error)
	// Get all results (limited)
	GetAllResults(ctx context.Context, limit int64) ([]Result, error)
	// Get lifetime stats for all workers, ordered by total keys scanned
	GetAllWorkerLifetimeStats(ctx context.Context) ([]WorkerStatsLifetime, error)
	// Get daily aggregates for all workers, combining archived and recent history
	GetGlobalDailyStats(ctx context.Context, sinceDate interface{}) ([]GetGlobalDailyStatsRow, error)
	// Get a specific job by ID
	GetJobByID(ctx context.Context, id int64) (Job, error)
	// Get jobs by status
	GetJobsByStatus(ctx context.Context, arg GetJobsByStatusParams) ([]Job, error)
	// Get all jobs assigned to a specific worker
	GetJobsByWorker(ctx context.Context, workerID sql.NullString) ([]Job, error)
	// Get the next available nonce range for a specific prefix
	GetNextNonceRange(ctx context.Context, prefix28 []byte) (interface{}, error)
	// Get usage statistics per prefix
	GetPrefixUsage(ctx context.Context, limit int64) ([]GetPrefixUsageRow, error)
	// Get recent worker history records for the last N seconds
	GetRecentWorkerHistory(ctx context.Context, arg GetRecentWorkerHistoryParams) ([]WorkerHistory, error)
	// Find a result by private key
	GetResultByPrivateKey(ctx context.Context, privateKey string) (Result, error)
	// Find results by Ethereum address
	GetResultsByAddress(ctx context.Context, address string) ([]Result, error)
	// Get aggregated statistics
	GetStats(ctx context.Context) (StatsSummary, error)
	// Get worker information by ID
	GetWorkerByID(ctx context.Context, id string) (Worker, error)
	// Get daily aggregates for a worker, combining archived and recent history
	// We select and group by stats_date only, as worker_id is filtered to a single value
	GetWorkerDailyStats(ctx context.Context, arg GetWorkerDailyStatsParams) ([]GetWorkerDailyStatsRow, error)
	// Tracks the last prefix assigned to a worker to enable vertical exhaustion
	GetWorkerLastPrefix(ctx context.Context, workerID sql.NullString) (GetWorkerLastPrefixRow, error)
	// Get lifetime stats for a worker
	GetWorkerLifetimeStats(ctx context.Context, workerID string) (WorkerStatsLifetime, error)
	// Accept a full timestamp/time.Time parameter but compare only the month portion (YYYY-MM)
	GetWorkerMonthlyStats(ctx context.Context, arg GetWorkerMonthlyStatsParams) ([]WorkerStatsMonthly, error)
	// Get statistics per worker
	GetWorkerStats(ctx context.Context, limit int64) ([]GetWorkerStatsRow, error)
	// Get all workers of a specific type
	GetWorkersByType(ctx context.Context, workerType string) ([]Worker, error)
	// Insert a new result (found key)
	InsertResult(ctx context.Context, arg InsertResultParams) (Result, error)
	// Lease an existing batch to a worker
	LeaseBatch(ctx context.Context, arg LeaseBatchParams) (int64, error)
	// Lease an existing macro job to a worker (if not completed and available)
	LeaseMacroJob(ctx context.Context, arg LeaseMacroJobParams) (int64, error)
	// Insert a raw worker history record (tier 1)
	RecordWorkerStats(ctx context.Context, arg RecordWorkerStatsParams) error
	// Update job progress checkpoint
	UpdateCheckpoint(ctx context.Context, arg UpdateCheckpointParams) error
	// Update worker's total key count
	UpdateWorkerKeyCount(ctx context.Context, arg UpdateWorkerKeyCountParams) error
	// Insert or update worker heartbeat
	UpsertWorker(ctx context.Context, arg UpsertWorkerParams) error
}

var _ Querier = (*Queries)(nil)
