version: "2.0"

run:
  timeout: 5m
  issues-exit-code: 1
  modules-download-mode: readonly

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    check-shadowing: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet   
    - ineffassign
    - staticcheck
    - unused     
    - revive     
    - gocritic   
    - gosec
