version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  modules-download-mode: readonly
  tests: true

linters:
  disable-all: true 
  enable:
    - bodyclose
    - gosec
    - govet
    - errorlint
    - misspell
    - nestif
    - noctx
    - prealloc
    - sqlclosecheck
    - unconvert
    - unparam
    - errcheck
    - wrapcheck
    - staticcheck
    - ineffassign
    - unused
    - revive

linters-settings:
  revive:
    rules:
      - name: var-naming
        severity: warning
        disabled: false
        arguments:
          - ["ID"] # AllowList
          - ["VM"] # DenyList
          - - skip-initialism-name-checks: true
              upper-case-const: true
              skip-package-name-checks: true
              skip-package-name-collision-with-go-std: true
              extra-bad-package-names:
                - helpers
                - models
                - utils

issues:
  max-issues-per-linter: 0
  max-same-issues: 0 
  exclude-use-default: false