version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  modules-download-mode: readonly
  tests: true

linters:
  disable-all: true 
  enable:
    - bodyclose
    - gosec
    - govet
    - errorlint
    - misspell
    - nestif
    - noctx
    - prealloc
    - sqlclosecheck
    - unconvert
    - unparam
    - errcheck
    - wrapcheck
    - staticcheck
    - ineffassign
    - unused
    - revive

issues:
  max-issues-per-linter: 0
  max-same-issues: 0 
  exclude-use-default: false